// <auto-generated />
namespace MapProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCategoryId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCategoryId));
        
        string IMigrationMetadata.Id
        {
            get { return "201704292355240_add-CategoryId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
